# Generated by Django 6.0.3 on 2026-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Gender', models.CharField()),
                ('Courses', models.CharField()),
                ('Qualification', models.CharField()),
            ],
        ),
    ]
