# Generated by Django 6.0.3 on 2026-04-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='Registered_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Registered_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Courses',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Qualification',
            field=models.CharField(null=True),
        ),
    ]
