# Generated by Django 6.0.3 on 2026-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_dob_student_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Confirm_Password',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(null=True),
        ),
    ]
