# Generated by Django 6.0.3 on 2026-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_confirm_password_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Resume',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
