# Generated by Django 6.0.4 on 2026-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact_No', models.IntegerField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Courses', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Resume', models.FileField(upload_to='')),
                ('Profile_Pic', models.ImageField(upload_to='')),
                ('DOB', models.DateField()),
                ('Registered_Date_Time', models.DateTimeField()),
                ('Registered_Time', models.TimeField()),
            ],
        ),
    ]
