# Generated by Django 6.0.4 on 2026-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Contact_No',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Registered_Date_Time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Registered_Time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Resume',
        ),
        migrations.AddField(
            model_name='student',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Contact',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
