# Generated by Django 6.0.4 on 2026-04-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=40)),
                ('Stu_email', models.EmailField(max_length=254)),
                ('Stu_contact', models.IntegerField()),
                ('Stu_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='University_Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=30)),
                ('alloted_date', models.DateField()),
                ('created_by', models.CharField(max_length=30)),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
