# Generated by Django 6.0.4 on 2026-05-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=20, unique=True)),
                ('d_dis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=40)),
                ('Stu_email', models.EmailField(max_length=254, unique=True)),
                ('Stu_contact', models.IntegerField()),
                ('Stu_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='University_Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('alloted_date', models.DateField()),
                ('created_by', models.CharField(max_length=30)),
                ('Stu_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_writer', models.CharField(max_length=50)),
                ('book_sub', models.CharField(max_length=50)),
                ('book_price', models.CharField(max_length=50)),
                ('stu_roll', models.ManyToManyField(to='app.university_roll')),
            ],
        ),
    ]
